<?php
$page = [
    'home' => 'home.php',
    'error' => "error.php",
    'cart' => 'cart.php',
    'signup' => 'signup.php',
    'about' => 'about.php',
    'wheretobuy' => 'wheretobuy.php',
    'faq' => 'faq.php',
    'addproduct' => 'addproduct.php',
    'modifyproduct' => 'modifyproduct.php',
    'login' => 'login.php',
    'loginadmin' => 'loginadmin.php',
    'adminhome' => 'adminhome.php',
    'adminmessages' => 'adminmessages.php',
    'payment' => 'payment.php',
    'paymentsuccessful' => 'paymentsuccessful.php',
    'contact' => 'contact.php',
    'inbox' => 'inbox.php',
    'edit' => 'edit.php',
    'editproducts' => 'editproducts.php',
    'productsbuyed' => 'productsbuyed.php',
    'profile' => 'profile.php',
    'history' => 'history.php',
    'userinbox' => 'userinbox.php',
    'logout' => 'logout.php',
];